<template>
    <div class="row ">
        <div class="col">
            <div class="row">
                <div class="col">
                    <div class="font-exo text.muted display-1 text-center">
                        BOARDS
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="container">
                    <div class="bg-light my-2 p-2">
                        searCH
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="container">
                    <table class="table">
                        <thead>
                        <tr class="bg-light">
                            <th scope="col" class="text-center" style="width: 5%">#</th>
                            <th scope="col" class="text-center" style="width: 10%">Icon</th>
                            <th scope="col" style="width: 50%">Name</th>
                            <th scope="col" style="width: 35%">Description</th>
                        </tr>
                        </thead>
                        <transition-group tag="tbody" name="slide">
                            <tr :key=" 'row-' + index" v-for="(board, index) in app.boards" @click="openBoard(board.id)" class="bg-light">
                                <td scope="row" class="align-middle text-center text-body">{{ index }}</td>
                                <td class="align-middle"><img src="/img/theme/boards/board.png" class="board-icon d-block mx-auto" alt=""></td>
                                <td class="align-middle">{{ board.title }}</td>
                                <td class="align-middle">{{ board.description ? board.description : ' - '}}</td>
                            </tr>
                        </transition-group>
                    </table>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
    export default {
        name: "Boards",
        data: function() {
            return {
                app: {
                    boards  : [],
                    stagger : 0,
                }
            }
        },
        methods : {
            getBoards(){
                axios.get('leankit/boards',{'errorHandle' : true})
                    .then( response => {
                        //this.app.boards = response.data.boards;

                        response.data.boards.forEach( (obj, index) => {
                            setTimeout(() => {
                                this.app.boards.push(obj);
                            },(index * 210))
                        });
                    })
                    .catch( error => {
                        console.log(error);
                    });
            },
            openBoard(id){
                this.$router.push('board/'+ id);
            },

        },
        created() {
            this.getBoards();
        }
    }
</script>

<style lang="scss" scoped>
    /*.board{*/
    /*    text-align : center;*/

    /*    .info{*/
    /*        margin: 10px 0;*/
    /*        border-radius: 10px;*/

    /*        .title {*/
    /*            font-size: 1rem;*/
    /*            padding: 10px;*/
    /*            font-weight: bold;*/
    /*        }*/
    /*    }*/

    /*}*/
    table.table{
        border-radius: 1em;

        thead{
            th{
                border-top: 0 solid white;
            }
        }
        tbody{
            tr{
                cursor: pointer;
                transition: all 100ms 210ms ease-in;
                &:hover{
                    background-color: rgb(174, 213, 255) !important;
                    box-shadow: 10px 10px 30px -16px rgba(0,0,0,0.75);
                    transform: translateZ(260px) scale(1.1);


                    /*td:first-child {*/
                    /*    border-top-left-radius: 50px;*/
                    /*    border-bottom-left-radius: 50px;*/
                    /*}*/
                    /*td:last-child {*/
                    /*    border-bottom-right-radius: 50px;*/
                    /*    border-top-right-radius: 50px;*/
                    /*}*/
                }
                td{
                    transition: all 100ms 210ms ease-in;
                    .board-icon{
                        width: 50px;
                    }
                }
            }
        }
    }

    .slide-enter-active {
        -webkit-animation: slide-in-bottom .2s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
        animation: slide-in-bottom .2s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
    }


    /* ----------------------------------------------
     * Generated by Animista on 2019-8-4 23:30:0
     * w: http://animista.net, t: @cssanimista
     * ---------------------------------------------- */

    /**
     * ----------------------------------------
     * animation slide-in-bottom
     * ----------------------------------------
     */
    @-webkit-keyframes slide-in-bottom {
        0% {
            -webkit-transform: translateY(1000px);
            transform: translateY(1000px);
            opacity: 0;
        }
        100% {
            -webkit-transform: translateY(0);
            transform: translateY(0);
            opacity: 1;
        }
    }
    @keyframes slide-in-bottom {
        0% {
            -webkit-transform: translateY(1000px);
            transform: translateY(1000px);
            opacity: 0;
        }
        100% {
            -webkit-transform: translateY(0);
            transform: translateY(0);
            opacity: 1;
        }
    }











</style>